import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Header() {
  return (
    <header>
      <div>
        <nav>
          <div>
            <Link href="/contact">Contact</Link>
          </div>
          <div>
            <Link href="/">Home</Link>
          </div>
          <div>
            <Link href="/mountain">Mountain</Link>
          </div>
          <div>
            <Link href="/hotels">Hotels</Link>
          </div>
        </nav>
      </div>
    </header>
  );
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="antialiased">
        <Header />
        {children}
      </body>
    </html>
  );
}
